### ISSUE TITLE
No internet connection. Unable to download dependencies.

### ISSUE THREAD

**Issue by jusdMustafa** [Broly1/ocflashdrive#4]
when i run the script it's says No internet connection. Unable to download dependencies. in Arch Linux

**Comment by Broly1** [comment]
You need to be connected to the Internet to use the script because it has to download the tools to for.at the drive and unpack the files.
https://github.com/Broly1/ocfd/blob/4ce451d0511bf34d7d7450446782e71aa15a68cc/ocfd.sh#L125
